### ISSUE TITLE
IndexError for DE or MCMC fitting a 7-point event

### ISSUE THREAD

**Issue by shanencross** [ebachelet/pyLIMA#9]
When fitting a particular 7-point event with the DE or MCMC method, got IndexError.

This is the traceback for the DE fit error:

Traceback (most recent call last):
  File "pyLIMA_testing.py", line 37, in <module>
    my_event.fits[0].produce_outputs()
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microlfits.py", line 757, in produce_outputs
    outputs = microloutputs.LM_outputs(self)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 55, in LM_outputs
    figure_trajectory = plot_LM_ML_geometry(fit)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 673, in plot_LM_ML_geometry
    figure_axes.arrow(trajectory_x[index_trajectory_limits[0] + 10], trajectory_y[index_trajectory_limits[0] + 10],
IndexError: index 0 is out of bounds for axis 0 with size 0

Don't know if this occurs for all 7-point events or just the one I tested. Here is the contents of the V-band data file I loaded for the event:
0.000000E+00 2.491136E+01 2.199786E-01
4.177083E+00 2.472473E+01 1.905160E-01
8.354167E+00 2.468362E+01 1.845757E-01
1.311458E+01 2.330891E+01 6.399954E-02
1.729167E+01 2.348643E+01 7.338008E-02
2.205208E+01 2.485427E+01 2.105118E-01
2.622917E+01 2.491633E+01 2.208219E-01

**Comment by ebachelet** [comment]
Hi Shanen

Please update your pyLIMA version with a git pull to see if it still
bugging, it should be fixed now.

Cheers

2016-09-12 14:24 GMT-07:00 shanencross <notifications@github.com>:

**Comment by shanencross** [comment]
Just tested the current version.

The DE fit works now, but the MCMC fit for this file still gives the same error.

Traceback (most recent call last):
  File "pyLIMA_testing.py", line 75, in <module>
    main()
  File "pyLIMA_testing.py", line 72, in main
    return lima_test()
  File "pyLIMA_testing.py", line 40, in lima_test
    fit.produce_outputs()
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microlfits.py", line 761, in produce_outputs
    outputs = microloutputs.MCMC_outputs(self)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 126, in MCMC_outputs
    figure_geometry = plot_MCMC_ML_geometry(fit, best_chains)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 794, in plot_MCMC_ML_geometry
    figure_axes.arrow(trajectory_x[index_trajectory_limits[0] + 10], trajectory_y[index_trajectory_limits[0] + 10],
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ebachelet** [comment]
Hi Shenan

Sorry about this, I did not apply the correction everywhere.

Try again with the new version please.

Cheers

2016-09-12 15:01 GMT-07:00 shanencross <notifications@github.com>:

**Comment by shanencross** [comment]
git pulled again and tried with newest version. LM and DE fits still work, but still getting the same error with MCMC fit:

Traceback (most recent call last):
  File "pyLIMA_testing.py", line 76, in <module>
    main()
  File "pyLIMA_testing.py", line 73, in main
    return lima_test()
  File "pyLIMA_testing.py", line 41, in lima_test
    fit.produce_outputs()
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microlfits.py", line 761, in produce_outputs
    outputs = microloutputs.MCMC_outputs(self)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 126, in MCMC_outputs
    figure_geometry = plot_MCMC_ML_geometry(fit, best_chains)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 790, in plot_MCMC_ML_geometry
    figure_axes.arrow(trajectory_x[index_trajectory_limits[0]], trajectory_y[index_trajectory_limits[0]],
IndexError: index 0 is out of bounds for axis 0 with size 0
